import {loadEnv} from './loadEnv.ts';
const env = loadEnv();

const devconfig = {
  MODE: env.MODE,
  PORT: env.PORT,
  DB_URL: env.DB_URL,
  DB_NAME:env.DB_NAME,
  DB_PASS:env.DB_PASS,
  SALT_WORK_FACTOR: env.SALT_WORK_FACTOR,
  ACCESS_TOKEN_TTL: env.ACCESS_TOKEN_TTL,
  REFRESH_TOKEN_TTL: env.REFRESH_TOKEN_TTL,
  JWT_SECRET: env.JWT_SECRET,
  ACCESS_TOKEN_PUBLIC_KEY: env.ACCESS_TOKEN_PUBLIC_KEY,
  ACCESS_TOKEN_PRIVATE_KEY: env.ACCESS_TOKEN_PRIVATE_KEY,
  REFRESH_TOKEN_PUBLIC_KEY: env.REFRESH_TOKEN_PUBLIC_KEY,
  REFRESH_TOKEN_PRIVATE_KEY: env.REFRESH_TOKEN_PRIVATE_KEY,
};

export default devconfig;
